using System.Collections.Generic;
using EloBuddy.SDK.Menu;

namespace KappaUtility.Brain.Utility.Tracker.SpellTracker
{
    internal abstract class SpellTrackerBase
    {
        protected HashSet<SpellInfo> TrackableSpells = new HashSet<SpellInfo>
        {
            // Buffs
            new SpellInfo("Aatrox P", "Aatrox", 0, SpellType.Buff, "AatroxPassiveDeath"),
            new SpellInfo("Ahri W", "Ahri", 0, SpellType.Buff, "AhriFoxFire"),
            new SpellInfo("Ahri R", "Ahri", 0, SpellType.Buff, "AhriTumble"),
            new SpellInfo("Anivia P", "Anivia", 0, SpellType.Buff, "rebirth"),
            new SpellInfo("Alistar R", "Alistar", 0, SpellType.Buff, "FerociousHowl"),
            new SpellInfo("Annie E", "Annie", 0, SpellType.Buff, "MoltenShield"),
            new SpellInfo("Ashe Q", "Ashe", 0, SpellType.Buff, "AsheQAttack"),
            new SpellInfo("Blitzcrank E", "Blitzcrank", 0, SpellType.Buff, "PowerFist"),
            new SpellInfo("Braum E", "Braum", 0, SpellType.Buff, "braumeshieldbuff"),
            new SpellInfo("Corki E", "Corki", 0, SpellType.Buff, "GGun"),
            new SpellInfo("Darius Q", "Darius", 0, SpellType.Buff, "dariusqcast"),
            new SpellInfo("Darius W", "Darius", 0, SpellType.Buff, "DariusNoxianTacticsONH"),
            new SpellInfo("Draven Q", "Draven", 0, SpellType.Buff, "DravenSpinning"),
            new SpellInfo("Draven W", "Draven", 0, SpellType.Buff, "dravenfurybuff"),
            new SpellInfo("DrMundo R", "DrMundo", 0, SpellType.Buff, "Sadism"),
            new SpellInfo("Diana W", "Diana", 0, SpellType.Buff, "DianaShield"),
            new SpellInfo("Ekko E", "Ekko", 0, SpellType.Buff, "ekkoeattackbuff"),
            new SpellInfo("Elise W", "Elise", 0, SpellType.Buff, "EliseSpiderW"),
            new SpellInfo("Elise E", "Elise", 0, SpellType.Buff, "EliseSpiderE"),
            new SpellInfo("Evelynn W", "Evelynn", 0, SpellType.Buff, "EvelynnW"),
            new SpellInfo("FiddleSticks W", "FiddleSticks", 0, SpellType.Buff, "fearmonger_marker"),
            new SpellInfo("FiddleSticks R", "FiddleSticks", 0, SpellType.Buff, "Crowstorm"),
            new SpellInfo("Fiora W", "Fiora", 0, SpellType.Buff, "FioraW"),
            new SpellInfo("Fiora E", "Fiora", 0, SpellType.Buff, "FioraE"),
            new SpellInfo("Fizz W", "Fizz", 0, SpellType.Buff, "FizzSeastonePassive"),
            new SpellInfo("Garen Q", "Garen", 0, SpellType.Buff, "GarenQ"),
            new SpellInfo("Garen W", "Garen", 0, SpellType.Buff, "GarenW"),
            new SpellInfo("Garen E", "Garen", 0, SpellType.Buff, "GarenE"),
            new SpellInfo("Gnar E", "Gnar", 0, SpellType.Buff, "gnareattackspeed"),
            new SpellInfo("Galio W", "Galio", 0, SpellType.Buff, "GalioBulwark"),
            new SpellInfo("Galio R", "Galio", 0, SpellType.Buff, "GalioIdolOfDurand"),
            new SpellInfo("Gragas W", "Gragas", 0, SpellType.Buff, "gragaswattackbuff"),
            new SpellInfo("Hecarim W", "Hecarim", 0, SpellType.Buff, "HecarimW"),
            new SpellInfo("Hecarim E", "Hecarim", 0, SpellType.Buff, "hecarimrampspeed"),
            new SpellInfo("Illaoi W", "Illaoi", 0, SpellType.Buff, "IllaoiW"),
            new SpellInfo("Irelia W", "Irelia", 0, SpellType.Buff, "ireliahitenstylecharged"),
            new SpellInfo("Irelia R", "Irelia", 0, SpellType.Buff, "IreliaTranscendentBladesSpell"),
            new SpellInfo("Janna E", "Janna", 0, SpellType.Buff, "EyeOfTheStorm"),
            new SpellInfo("Janna R", "Janna", 0, SpellType.Buff, "ReapTheWhirlwind"),
            new SpellInfo("JarvanIV W", "JarvanIV", 0, SpellType.Buff, "JarvanIVGoldenAegis"),
            new SpellInfo("Jax W", "Jax", 0, SpellType.Buff, "JaxEmpowerTwo"),
            new SpellInfo("Jax E", "Jax", 0, SpellType.Buff, "JaxCounterStrike"),
            new SpellInfo("Jax R", "Jax", 0, SpellType.Buff, "jaxrelentlessassaultspeed"),
            new SpellInfo("Jhin Crit", "Jhin", 0, SpellType.Buff, "jhinpassiveattackbuff"),
            new SpellInfo("Jhin Reload", "Jhin", 0, SpellType.Buff, "JhinPassiveReload"),
            new SpellInfo("Jhin E", "Jhin", 0, SpellType.Buff, "jhinespotteddebuff"),
            new SpellInfo("Karma E", "Karma", 0, SpellType.Buff, "KarmaSolKimShield"),
            new SpellInfo("Karma R", "Karma", 0, SpellType.Buff, "KarmaMantra"),
            new SpellInfo("Karthus R", "Karthus", 0, SpellType.Buff, "karthusfallenonecastsound"),
            new SpellInfo("Kassadin Q", "Kassadin", 0, SpellType.Buff, "NullLance"),
            new SpellInfo("Kassadin W", "Kassadin", 0, SpellType.Buff, "NetherBlade"),
            new SpellInfo("Kayle W", "Kayle", 0, SpellType.Buff, "JudicatorDivineBlessing"),
            new SpellInfo("Kayle E", "Kayle", 0, SpellType.Buff, "JudicatorRighteousFury"),
            new SpellInfo("Kayle R", "Kayle", 0, SpellType.Buff, "JudicatorIntervention"),
            new SpellInfo("Kennen E", "Kennen", 0, SpellType.Buff, "KennenLightningRush"),
            new SpellInfo("Kennen R", "Kennen", 0, SpellType.Buff, "KennenShurikenStorm"),
            new SpellInfo("Khazix R", "Khazix", 0, SpellType.Buff, "KhazixR"),
            new SpellInfo("Kindred E", "Kindred", 0, SpellType.Buff, "KindredERefresher"),
            new SpellInfo("KogMaw P", "KogMaw", 0, SpellType.Buff, "KogMawIcathianSurprise"),
            new SpellInfo("KogMaw W", "KogMaw", 0, SpellType.Buff, "KogMawBioArcaneBarrage"),
            new SpellInfo("LeeSin W", "LeeSin", 0, SpellType.Buff, "blindmonkwoneshield"),
            new SpellInfo("Leona Q", "Leona", 0, SpellType.Buff, "LeonaShieldOfDaybreak"),
            new SpellInfo("Leona W", "Leona", 0, SpellType.Buff, "LeonaSolarBarrier"),
            new SpellInfo("Lissandra R", "Lissandra", 0, SpellType.Buff, "LissandraRSelf"),
            new SpellInfo("Lucian P", "Lucian", 0, SpellType.Buff, "LucianPassiveBuff"),
            new SpellInfo("Lucian R", "Lucian", 0, SpellType.Buff, "LucianR"),
            new SpellInfo("Lulu W", "Lulu", 0, SpellType.Buff, "luluwbuff"),
            new SpellInfo("Lulu E", "Lulu", 0, SpellType.Buff, "lulufaerieshield"),
            new SpellInfo("Lulu R", "Lulu", 0, SpellType.Buff, "LuluR"),
            new SpellInfo("Lux W", "Lux", 0, SpellType.Buff, "luxprismaticwaveshieldself"),
            new SpellInfo("Malphite W", "Malphite", 0, SpellType.Buff, "MalphiteCleave"),
            new SpellInfo("Maokai R", "Maokai", 0, SpellType.Buff, "MaokaiDrain3"),
            new SpellInfo("MasterYi W", "MasterYi", 0, SpellType.Buff, "Meditate"),
            new SpellInfo("MasterYi E", "MasterYi", 0, SpellType.Buff, "wujustylesuperchargedvisual"),
            new SpellInfo("MasterYi R", "MasterYi", 0, SpellType.Buff, "Highlander"),
            new SpellInfo("MissFortune W", "MissFortune", 0, SpellType.Buff, "MissFortuneViciousStrikes"),
            new SpellInfo("MissFortune R", "MissFortune", 0, SpellType.Buff, "missfortunebulletsound"),
            new SpellInfo("Morgana E", "Morgana", 0, SpellType.Buff, "BlackShield"),
            new SpellInfo("Nami E", "Nami", 0, SpellType.Buff, "NamiE"),
            new SpellInfo("Nasus Q", "Nasus", 0, SpellType.Buff, "NasusQ"),
            new SpellInfo("Nasus R", "Nasus", 0, SpellType.Buff, "NasusR"),
            new SpellInfo("Nautilus W", "Nautilus", 0, SpellType.Buff, "nautiluspiercinggazeshield"),
            new SpellInfo("Nidalee Q", "Nidalee", 0, SpellType.Buff, "Takedown"),
            new SpellInfo("Nidalee E", "Nidalee", 0, SpellType.Buff, "PrimalSurge"),
            new SpellInfo("Nocturne W", "Nocturne", 0, SpellType.Buff, "NocturneShroudofDarkness"),
            new SpellInfo("Nunu W", "Nunu", 0, SpellType.Buff, "BloodBoil"),
            new SpellInfo("Nunu R", "Nunu", 0, SpellType.Buff, "AbsoluteZero"),
            new SpellInfo("Orianna E", "Orianna", 0, SpellType.Buff, "orianaredactshield"),
            new SpellInfo("Olaf W", "Olaf", 0, SpellType.Buff, "OlafFrenziedStrikes"),
            new SpellInfo("Olaf R", "Olaf", 0, SpellType.Buff, "OlafRagnarok"),
            new SpellInfo("Pantheon E", "Pantheon", 0, SpellType.Buff, "pantheonesound"),
            new SpellInfo("Pantheon R", "Pantheon", 0, SpellType.Buff, "PantheonRJump"),
            new SpellInfo("Riven P", "Riven", 0, SpellType.Buff, "RivenTriCleave"),
            new SpellInfo("Riven Q1", "Riven", 0, SpellType.Buff, "riventricleavesoundone"),
            new SpellInfo("Riven Q2", "Riven", 0, SpellType.Buff, "riventricleavesoundtwo"),
            new SpellInfo("Riven Q3", "Riven", 0, SpellType.Buff, "riventricleavesoundthree"),
            new SpellInfo("Riven E", "Riven", 0, SpellType.Buff, "RivenFeint"),
            new SpellInfo("Riven R1", "Riven", 0, SpellType.Buff, "rivenwindslashready"),
            new SpellInfo("Riven R2", "Riven", 0, SpellType.Buff, "RivenFengShuiEngine"),
            new SpellInfo("Tristana Q", "Tristana", 0, SpellType.Buff, "TristanaQ"),
            new SpellInfo("Tristana E", "Tristana", 0, SpellType.Buff, "tristanaecharge"),
            new SpellInfo("Tryndamere R", "Tryndamere", 0, SpellType.Buff, "UndyingRage"),
            new SpellInfo("Udyr Q", "Udyr", 0, SpellType.Buff, "udyrtigerpunch"),
            new SpellInfo("Udyr W", "Udyr", 0, SpellType.Buff, "udyrturtleactivation"),
            new SpellInfo("Udyr E", "Udyr", 0, SpellType.Buff, "udyrbearactivation"),
            new SpellInfo("Udyr R", "Udyr", 0, SpellType.Buff, "UdyrPhoenixActivation"),
            new SpellInfo("Volibear Q", "Volibear", 0, SpellType.Buff, "VolibearQ"),
            new SpellInfo("Volibear W", "Volibear", 0, SpellType.Buff, "volibearwparticle"),
            new SpellInfo("Volibear R", "Volibear", 0, SpellType.Buff, "volibearrapplicator"),
            new SpellInfo("Zac E", "Zac", 0, SpellType.Buff, "ZacE"),
            new SpellInfo("Zac R", "Zac", 0, SpellType.Buff, "ZacR"),
            new SpellInfo("Vayne Q", "Vayne", 0, SpellType.Buff, "vaynetumblebonus"),

            // Minions
            new SpellInfo("Annie Tibbers", "Annie", 45f, SpellType.Minion, "AnnieTibbers"),
            new SpellInfo("Shaco Clone", "Shaco", 18f, SpellType.Minion, "Shaco"),
            new SpellInfo("Leblanc Clone", "Leblanc", 8f, SpellType.Minion, "Leblanc"),
            new SpellInfo("Malzahar Voidling", "Malzahar", 12f, SpellType.Minion, "MalzaharVoidling"),
            new SpellInfo("Maokai E", "Maokai", 40f, SpellType.Minion, "MaokaiSproutling"),

            // GameObject
            new SpellInfo("Akali W", "Akali", 8f, SpellType.GameObject, "Akali_Base_smoke_bomb_tar_team_green.troy"),
            new SpellInfo("Brand W", "Brand", 0.75f, SpellType.GameObject, "Brand_Base_W_POF_tar_green.troy"),
            new SpellInfo("Cho'gath Q", "ChoGath", 0.625f, SpellType.GameObject, "rupture_cas_01_green_team.troy"),
            new SpellInfo("Cassiopeia W", "Cassiopeia", 5f, SpellType.GameObject, "Cassiopeia_Base_W_WCircle_tar_green.troy"),
            new SpellInfo("Draven Q", "Draven", 1f, SpellType.GameObject, "Draven_Base_Q_reticle.troy"),
            new SpellInfo("Ekko W", "Ekko", 4.5f, SpellType.GameObject, "Ekko_Base_W_Indicator.troy"),
            new SpellInfo("Elise W", "Elise", 3f, SpellType.GameObject, "Elise_Base_W_volatile_cas.troy"),
            new SpellInfo("Fizz R", "Fizz", 1.5f, SpellType.GameObject, "Fizz_Base_R_Ring_Green.troy"),
            new SpellInfo("Gragas Q", "Gragas", 4f, SpellType.GameObject, "Gragas_Base_Q_Enemy.troy"),
            new SpellInfo("Graves W", "Graves", 4f, SpellType.GameObject, "Graves_SmokeGrenade_Cloud_Team_Green.troy"),
            new SpellInfo("JarvanIV E", "JarvanIV", 8f, SpellType.GameObject, "JarvanDemacianStandard_tar_green.troy"),
            new SpellInfo("Jayce E", "Jayce", 4f, SpellType.GameObject, "Jayce_Base_accel_gate_start.troy"),
            new SpellInfo("Jhin E", "Jhin", 2f, SpellType.GameObject, "Jhin_Base_E_Trap_activate.troy"),
            new SpellInfo("Karma Q", "Karma", 1.5f, SpellType.GameObject, "Karma_Base_Q_impact_R_01.troy"),
            new SpellInfo("Karthus W", "Karthus", 5f, SpellType.GameObject, "Karthus_Base_W_Wall.troy"),
            new SpellInfo("Kindred W", "Kindred", 8.5f, SpellType.GameObject, "Kindred_Base_W_Indicator_Green.troy"),
            new SpellInfo("Kindred R", "Kindred", 4f, SpellType.GameObject, "Kindred_Base_R_AOE.troy"),
            new SpellInfo("Lux E", "Lux", 5f, SpellType.GameObject, "Lux_Base_E_tar_aoe_green.troy"),
            new SpellInfo("MissFortune E", "MissFortune", 3f, SpellType.GameObject, "MissFortune_Base_E_Unit_Tar_green.troy"),
            new SpellInfo("Morgana W", "Morgana", 5f, SpellType.GameObject, "Morgana_Skin00_W_Tar_Green.troy"),
            new SpellInfo("Morgana W", "Morgana", 5f, SpellType.GameObject, "Morgana_Skin01_W_Tar_Green.troy"),
            new SpellInfo("Morgana W", "Morgana", 5f, SpellType.GameObject, "Morgana_Skin02_W_Tar_Green.troy"),
            new SpellInfo("Morgana W", "Morgana", 5f, SpellType.GameObject, "Morgana_Skin03_W_Tar_Green.troy"),
            new SpellInfo("Morgana W", "Morgana", 5f, SpellType.GameObject, "Morgana_Skin04_W_Tar_Green.troy"),
            new SpellInfo("Morgana W", "Morgana", 5f, SpellType.GameObject, "Morgana_Skin05_W_Tar_Green.troy"),
            new SpellInfo("Morgana W", "Morgana", 5f, SpellType.GameObject, "Morgana_Skin06_W_Tar_Green.troy"),
            new SpellInfo("Nasus E", "Nasus", 5f, SpellType.GameObject, "Nasus_E_Green_Ring.troy"),
            new SpellInfo("Nidalee W", "Nidalee", 120f, SpellType.GameObject, "Nidalee_Base_W_TC_Green.troy"),
            new SpellInfo("Orianna W", "Orianna", 3f, SpellType.GameObject, "Orianna_Base_W_Dissonance_ball_green.troy"),
            new SpellInfo("Orianna R", "Orianna", 0.5f, SpellType.GameObject, "Orianna_Base_R_VacuumIndicatorSelfRing.troy"),
            new SpellInfo("Orianna R", "Orianna", 0.5f, SpellType.GameObject, "Orianna_Base_R_VacuumIndicator.troy"),
            new SpellInfo("Olaf Q", "Olaf", 7.5f, SpellType.GameObject, "Olaf_Base_Q_Axe_Ally.troy"),
            new SpellInfo("Pantheon R", "Pantheon", 4.5f, SpellType.GameObject, "Pantheon_Base_R_indicator_green.troy"),
            new SpellInfo("Zac P", "Zac", 8f, SpellType.GameObject, "Zac_Base_P_Chunk.troy"),
        };

        protected List<DetectedSpellInfo> DetectedSpells = new List<DetectedSpellInfo>(); 

        internal abstract void Load(bool SpectatorMode = false, Menu mainMenu = null);
    }
}